### ISSUE TITLE
request is not defined

### ISSUE THREAD

**Issue by shikhar022** [eemp/mozaik-ext-table#1]
I am receiving the following error when I used url instead of path to json

ReferenceError: request is not defined
[1]     at getAPIData (<project-src-dir>/node_modules/mozaik-ext-table/src/client.js:41:3)

Please help I am stuck here. And the config.yml for the mozaik dashboard is as follows:

- columns: 4
  rows:    4
  title:   Mozaïk PS Demo Dashboard
  widgets:
  -
    extension:   table
    widget:      Table
    title:       Team
    fields:
      -
        Name:   '{name}'
      -
        Level:  '{designation}'
    url:        http://localhost:8081/rest/employees
    columns:     4
    rows:        4
    x:           0
    y:           0

**Comment by eemp** [comment]
Thanks for reporting @shikhar022.

Looks like a silly error on my part that I just released a fix for.  Could you please try updating to `mozaik-ext-table@0.1.0` and let me know if that helps resolve the issue?

**Comment by shikhar022** [comment]
Works now. Thanks :+1:
